export const dummyData = [
  {
    type: "text",
    name: "firstName",
    label: "First Name",
    placeholder: "First Name",
    variant: "static",
    required: true,
    errorText: "First name should contain 3 to 20 letters only ",
  },
  {
    type: "text",
    name: "lastName",
    label: "Last Name",
    placeholder: "Last Name",
    variant: "static",
    required: true,
    errorText: "Last name should contain 3 to 20 letters only",
  },
  {
    type: "email",
    name: "email",
    label: "Email",
    placeholder: "Email",
    variant: "static",
    required: true,
    errorText: "Invalid Email address ",
  },
  {
    type: "radio",
    name: "gender",
    label: "Gender",
    options: ["Male", "Female", "Transgender"],
    required: true,
    errorText: "Please select your Gender",
  },
  {
    type: "text",
    name: "mobile",
    label: "Mobile",
    placeholder: "Mobile",
    variant: "static",
    required: true,
    errorText: "Invalid mobile number",
  },
  {
    type: "date",
    name: "dob",
    label: "Date of Birth",
    variant: "static",
    required: true,
    errorText: "Age must be greater than 18 years",
  },
  {
    type: "date",
    name: "doj",
    label: "Date of Joining",
    variant: "static",
    required: true,
    errorText: "Joining date should be within 30 days",
  },
];
