export const staticFormData = [
  {
    type: "text",
    label: "Label",
    placeholder: "Placeholder",
    variant: "static",
  },
  {
    type: "text",
    label: "Label",
    placeholder: "Placeholder",
    variant: "static",
  },
  {
    type: "text",
    label: "Label",
    placeholder: "Placeholder",
    variant: "static",
    helperText: "Basic helper text goes here",
  },
  {
    type: "text",
    label: "Name",
    placeholder: "Placeholder",
    variant: "static",
    helperText: "Basic helper text goes here",
    value: "Jhon Doe",
  },
  {
    type: "text",
    label: "Name",
    placeholder: "Placeholder",
    variant: "static",
    helperText: "Is that really your name?",
    value: "jhondoe@gmail.com",
  },
  {
    type: "text",
    label: "Label - Optional",
    placeholder: "Placeholder",
    variant: "static",
  },
  {
    type: "password",
    label: "Label",
    placeholder: "Placeholder",
    variant: "static",
    value: "98JD7h7",
  },
  {
    type: "text",
    label: "Label",
    placeholder: "Placeholder",
    variant: "static",
    value: "98JD7h7",
  },
];
